### ISSUE TITLE
scala.reflect.internal.MissingRequirementError

### ISSUE THREAD

**Issue by rishHashedin** [NVIDIA-AI-IOT/deepstream_360_d_smart_parking_application#9]
I was running the spark job to generate playback data and I got this:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.nvidia.ds:stream-360:jar:1.0
[WARNING] 'build.plugins.plugin.version' for org.scala-tools:maven-scala-plugin is missing. @ line 125, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ----------------------< com.nvidia.ds:stream-360 >----------------------
[INFO] Building stream-360 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for harsha2010:magellan:jar:1.0.5-s_2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ stream-360 ---
[INFO] Deleting /home/hasher/GIT/deepstream_360_d_smart_parking_application/stream/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ stream-360 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ stream-360 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:compile (default) @ stream-360 ---
[INFO] Checking for multiple versions of scala
[WARNING] Invalid POM for harsha2010:magellan:jar:1.0.5-s_2.11, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  com.twitter:chill_2.11:0.8.0 requires scala version: 2.11.7
[WARNING] Multiple versions of scala libraries detected!
[INFO] includes = [**/*.java,**/*.scala,]
[INFO] excludes = []
[INFO] /home/hasher/GIT/deepstream_360_d_smart_parking_application/stream/src/main/scala:-1: info: compiling
[INFO] Compiling 14 source files to /home/hasher/GIT/deepstream_360_d_smart_parking_application/stream/target/classes at 1558086975704
[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
[INFO] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[INFO] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[INFO] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
[INFO] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
[INFO] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
[INFO] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[INFO] 	at scala.tools.nsc.Driver.process(Driver.scala:51)
[INFO] 	at scala.tools.nsc.Driver.main(Driver.scala:64)
[INFO] 	at scala.tools.nsc.Main.main(Main.scala)
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO] 	at org_scala_tools_maven_executions.MainHelper.runMain(MainHelper.java:161)
[INFO] 	at org_scala_tools_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.890 s
[INFO] Finished at: 2019-05-17T15:26:17+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scala-tools:maven-scala-plugin:2.15.2:compile (default) on project stream-360: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by timhartill** [comment]
I am facing exactly the same error. Can anyone advise the path to resolution?

**Comment by aiyerganapathy** [comment]
We are not able to reproduce this error. We have tested this successfully on Ubuntu 16.04 with Java 1.8.

**Comment by timhartill** [comment]
Thanks for looking. I am using Ubuntu 18.04 LTS. 
 
java -version says:

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

Any suggestion to resolve?

**Comment by timhartill** [comment]
I resolved this by installing an earlier version of java:
sudo apt install openjdk-8-jdk

I suggest updating the instructions in the readme from sudo apt install default-jdk to sudo apt install openjdk-8-jdk

Thanks for your help.

**Comment by rishHashedin** [comment]
> Thanks for looking. I am using Ubuntu 18.04 LTS.
> 
> java -version says:
> 
> openjdk version "11.0.3" 2019-04-16
> OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
> OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
> 
> Any suggestion to resolve?

Mine is also the same

**Comment by aiyerganapathy** [comment]
@timhartill Awesome. Glad to hear that the issue was resolved.
@rishHashedin I was able to generate data in Ubuntu 18.04 after installing JDK 1.8. 
You can install it by running the following command
`sudo apt install openjdk-8-jdk`
I have also updated the README.
